BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "petalinux-artiq"
BBFILE_PATTERN_petalinux-artiq = "^${LAYERDIR}/"
BBFILE_PRIORITY_petalinux-artiq = "6"

LAYERDEPENDS_petalinux-artiq = "core"
LAYERSERIES_COMPAT_petalinux-artiq = "scarthgap"
