BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "artiq"
BBFILE_PATTERN_artiq = "^${LAYERDIR}/"
BBFILE_PRIORITY_artiq = "6"

LAYERDEPENDS_artiq = "core"
LAYERSERIES_COMPAT_artiq = "scarthgap"
