BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "artiq-xilinx"
BBFILE_PATTERN_artiq-xilinx = "^${LAYERDIR}/"
BBFILE_PRIORITY_artiq-xilinx = "6"

LAYERDEPENDS_artiq-xilinx = "core"
LAYERSERIES_COMPAT_artiq-xilinx = "scarthgap"
