require conf/machine/zynqmp-generic.conf

INITRAMFS_IMAGE = "artiqlinux-initramfs-image"
INITRAMFS_FSTYPES = "cpio.gz.u-boot"
RAMDISK_IMAGE = "${INITRAMFS_IMAGE}-${MACHINE}.${INITRAMFS_FSTYPES}"
KERNEL_ROOT_RAMDISK = "root=/dev/\${bootdev}2"
KERNEL_COMMAND_APPEND = "panic=5"
IMAGE_BOOT_FILES += "${RAMDISK_IMAGE}"
IMAGE_FSTYPES += "wic"
