require conf/distro/petalinux.conf

VIRTUAL-RUNTIME_base-utils = "packagegroup-core-full-cmdline"
VIRTUAL-RUNTIME_base-utils-hwclock = "util-linux-hwclock"
VIRTUAL-RUNTIME_base-utils-syslog = ""
VIRTUAL-RUNTIME_login_manager = "shadow-base"

PACKAGECONFIG:remove:pn-vim = "x11 gtkgui"

# SEE: meta-petalinux/conf/distro/petalinux.conf
EXTRA_USERS_PARAMS = " \
    useradd -p '' -- petalinux ; \
    usermod -a -Gadm,sudo,audio,video,input,plugdev,dialout -- petalinux ; \
"

# SEE: meta-petalinux/classes/plnx-useradd-sudoers.bbclass
EXTRA_USERS_SUDOERS = " \
    %sudo ALL=(ALL:ALL) ALL ; \
"
